config/routes.rb
Rails.application.routes.draw do
  resources :profile_users
  resources :companies, only: [:new, :edit, :create, :update]
  resources :positions do
    resources :applicants, only: [:index]
  end
  resources :applicants, only: [:new, :create]

  devise_for :users, controllers: { registrations: 'user' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#index'

  get "/vaga/:slug", to: "positions#public_position", as: :public_position
end

app/models/applicant.rb
require 'csv'

class Applicant < ApplicationRecord
  belongs_to :user
  belongs_to :position

  validates :name, :email, :phone, presence: true

# Método para calcular a idade com base na data de nascimento (birthdate)
def calculate_age
  return if brithday.nil?

  now = Time.now.utc.to_date
  dob = self.brithday.to_date
  age = now.year - dob.year
  age -= 1 if now.month < dob.month || (now.month == dob.month && now.day < dob.day)
  return age
end


  def verifica_idade
    idade = self.calculate_age
    if (idade <=13)
      return "menor"
    elsif(idade > 13 && idade < 18)
      return "aprendiz"
    else
      return "efetivo"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brazil.rb
class Brazil
  class << self
    def states
      {
        'AC': 'Acre',
        'AL': 'Alagoas',
        'AP': 'Amapá',
        'AM': 'Amazonas',
        'BA': 'Bahia',
        'CE': 'Ceará',
        'DF': 'Distrito Federal',
        'ES': 'Espírito Santo',
        'GO': 'Goiás',
        'MA': 'Maranhão',
        'MT': 'Mato Grosso',
        'MS': 'Mato Grosso do Sul',
        'MG': 'Minas Gerais',
        'PA': 'Pará',
        'PB': 'Paraíba',
        'PR': 'Paraná',
        'PE': 'Pernambuco',
        'PI': 'Piauí',
        'RJ': 'Rio de Janeiro',
        'RN': 'Rio Grande do Norte',
        'RS': 'Rio Grande do Sul',
        'RO': 'Rondônia',
        'RR': 'Roraima',
        'SC': 'Santa Catarina',
        'SP': 'São Paulo',
        'SE': 'Sergipe',
        'TO': 'Tocantins'
      }
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :positions # atualizado
  has_one_attached :logo
  validates :name, :url, :logo, presence: true
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :company
  has_many :applicants

  enum career: [:developer, :business_inteligence, :information_technology,
                :design, :product, :technology, :other]
  enum contract: [:clt, :pj, :match]

  validates :name, :career, :contract, :city, :state, :summary, presence: true

  before_save :set_slug

  def is_remote
    if self.remote == true
      return true
    else
      return false
    end
  end

  def is_full_time
    if self.full_time == true
      return true
    else
      return false
    end
  end

  private

  def set_slug
    self.slug = "#{self.company.name.parameterize}-#{self.name.parameterize}"
  end

  def self.ransackable_attributes(auth_object = nil)
    ["career", "city", "company_id", "contract", "created_at", "description", "id", "name", "publish", "remote", "slug", "state", "summary", "updated_at"]
  end


end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/profile_user.rb
class ProfileUser < ApplicationRecord
  belongs_to :profile
  belongs_to :user
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/models/skill_applicant.rb
class SkillApplicant < ApplicationRecord
  belongs_to :skill
  belongs_to :applicant
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_one :company
  has_many :applicants
  has_many :profile_users
  has_many :profiles, through: :profile_users
  attr_accessor :profile_id

  def profile
    profile_user = ProfileUser.find_by(user_id: self.id)
    Profile.find_by(id: profile_user.profile_id)
  end

  def create_default_profile(profile_id)
    if profile_id.present?
      ProfileUser.create(user_id: self.id, profile_id: profile_id)
    else
      ProfileUser.create(user_id: self.id, profile_id: Profile.find_by(name:"Candidato").id)
    end
  end
end

app/models/user_position.rb
class UserPosition < ApplicationRecord
  belongs_to :User
  belongs_to :Position
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @q = Position.ransack(params[:q])
    @positions = @q.result.page(params[:page]).per(params[:per])
    @contracts = [['CLT', 0], ['PJ', 1], ['A combinar', 2]]
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_company, :set_i18n_careers, :set_i18n_contracts, except: [:public_position]
  before_action :set_position, only: [:edit, :show, :update]
  def index
    @positions = @company.positions
  end

  def new
    @position = @company.positions.new
  end

  def edit
  end

  def show
  end

  def create
    @position = @company.positions.new(params_position)
    if @position.save
      flash[:success] = 'Vaga cadastrada com sucesso'
      redirect_to positions_path
    else
      render :new
    end
  end

  def update
    if @position.update(params_position)
      redirect_to positions_path
    else
      render :edit
    end
  end

  def public_position
    @position = Position.find_by(slug: params[:slug])
    @applicant = current_user.applicants.new(position_id: @position.id) if user_signed_in?

    respond_to do |format|
      format.html
      format.js { render partial: 'applicants/new' }
    end
  end

  def public_position
    @position = Position.find_by(slug: params[:slug])
    @applicant = current_user.applicants.new(position_id: @position.id) if user_signed_in?
  end

  private

  def set_position
    @position = @company.positions.find(params[:id])
  end

  def params_position
    params.require(:position).permit(:name, :career, :contract, :remote, :publish, :city, :state, :summary, :description, :full_time)
  end

  def set_company
    redirect_to new_company_path if current_user.company.nil?
    @company = current_user.company
  end

  def set_i18n_careers
    @careers = I18n.t('activerecord.attributes.position.careers')
  end

  def set_i18n_contracts
    @contracts = I18n.t('activerecord.attributes.position.contracts')
  end
end

app/controllers/skill_controller.rb
class SkillController < ApplicationController

end

app/controllers/user_controller.rb
class UserController < Devise::RegistrationsController
  
  def create
    super do |user|
      binding.pry
      user.create_default_profile(params[:user][:profile_id])
    end
  end

end
  

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
    def dynamic_url_company
        if current_user.company.present? && current_user.company.try(:id).present?
            edit_company_path(current_user.company)
        else
            new_company_path
        end
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
  def text_position(position)
    "A empresa #{position.company.name} em #{position.city} está com a vaga de #{position.name}. Veja mais detalhes no nosso mural! #{url_position(position)}"
  end

  def url_position(position)

    public_position_url(position.slug)
  end

  def career_name(career)
    
    I18n.t('activerecord.attributes.position.careers')[career.to_sym]
  end

  def contract_name(contract)
    I18n.t('activerecord.attributes.position.contracts')[contract.to_sym]
  end

  def modality(position)
    position.remote ? 'Remoto' : 'Presencial'
  end
end

app/helpers/profile_users_helper.rb
module ProfileUsersHelper
end

app/helpers/skill_helper.rb
module SkillHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/positions/_form.html.haml
= simple_form_for @position do |f|
  = f.input :name
  = f.input :career, as: :select, collection: @careers, label_method: :second, value_method: :first, include_blank: false, selected: @position.career
  = f.input :contract, as: :select, collection: @contracts, label_method: :second, value_method: :first, include_blank: false, selected: @position.contract
  = f.input :remote
  = f.input :full_time,label: "integral"
  = f.input :publish
  = f.input :city
  -# = f.input :state
  = f.input :state, as: :select, collection: Brazil.states, label_method: :second, value_method: :first
  = f.input :summary, maxlength: 360, input_html: { class: 'count-textarea', rows: 4 }
  = f.input :description
  = f.button :submit, class: 'btn btn-primary'

app/views/positions/_position.html.haml
.card.card-position
  .card-body
    .container.conteiner-card
      .row
        .col-2
          = image_tag position.company.logo, alt: "Logo marca da empresa #{position.company.name}", class: 'card-img-top'
        .col-10
          %h4= position.name
          %h5= "#{I18n.t('activerecord.attributes.position.careers')[position.career.to_sym]} - #{position.city} - #{I18n.t('activerecord.attributes.position.contracts')[position.contract.to_sym]}"
          %p= position.summary
          .row
            .col-sm.mt-3
              = link_to 'Ver mais', public_position_path(position.slug), class: 'btn btn-danger'
              - if user_signed_in?
                = link_to 'Candidatar-se', public_position_path(position.slug), {:remote => true, "data-target" => "modal", "data-backdrop" => "modal", 'data-backdrop' => 'static', 'data-keyboard' => 'false', class: 'btn btn-success'}
            .col-sm.text-right.mt-3.group-social-network
              = render partial: 'shared/social_network', locals: {position: position}

app/views/positions/create.html.haml
%h1 Positions#create
%p Find me in app/views/positions/create.html.haml

app/views/positions/edit.html.haml
%h2 Editar Vaga
= render 'form'

app/views/positions/index.html.haml
%h2 Minhas vagas

%table.table
  %thead.thead-dark
    %tr
      %th{:scope => "col"} Título
      %th{:scope => "col"} Carreira
      %th{:scope => "col"} Local
      %th{:scope => "col"} Tipo de contrato
      %th{:scope => "col"} Candidaturas
      %th{:scope => "col"} Ações
  %tbody
    - @positions.each do |position|
      %tr
        %th{:scope => "row"}= position.name
        %td= career_name(position.career)
        %td= modality(position) # aplicar helper se não for remoto devemos mostra os estado e cidade da vaga
        %td= contract_name(position.contract)
        %td 
          - if position.applicants.size > 0
            = link_to "Ver aplicações (#{position.applicants.count})", position_applicants_path(position), class: 'btn btn-warning btn-sm'
        %td
          = link_to 'Editar', edit_position_path(position), class: 'btn btn-outline-info'

app/views/positions/new.html.haml
%h2 Cadastrar Vaga 
= render 'form'

app/views/positions/public_position.html.haml
%h2= "#{@position.name} - #{@position.company.name}"
%p= "#{career_name(@position.career)} - #{@position.city} / #{modality(@position)}, #{@position.state} - #{contract_name(@position.contract)}"

= @position.description

%br/
%h5 Compartilhar
= render partial: 'shared/social_network', locals: {position: @position}

.wrapper-form-applicant
  - if user_signed_in?
    %p= "Insira suas informações abaixo para se candidatar à vaga de #{@position.name}"
    = render 'applicants/form'
  - else
    %p Você precisa está logado para se candidatar

  

app/views/positions/show.html.haml
%h1 Positions#show
%p Find me in app/views/positions/show.html.haml

app/views/positions/update.html.haml
%h1 Positions#update
%p Find me in app/views/positions/update.html.haml